language: rust
cache: cargo
dist: trusty
os: 
  - linux
  - osx

# Run builds for all the supported trains
rust:
  - nightly
  - beta
  - stable
  - 1.8.0

# The main build
script:
  - cargo build
  - cargo test --release
  - cargo test --release -- --ignored --nocapture --test-threads=1
